### ISSUE TITLE
🐞 错误报告 - 本地vite运行OK，vercel部署报跨域错误

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/MidJourney-Web#14]
# 错误报告 🐞

如果您在使用此项目时遇到了错误，请在此报告，我们会尽快解决此问题。

## 错误描述 🤔

本地vite运行OK，vercel部署报跨域错误

## 附加信息 📝
![img_v2_e9596e07-6a0
0-4ac2-9e60-6d5b2abc39bg](https://github.com/ConnectAI-E/MidJourney-Web/assets/50035229/df09ebf8-6619-449c-9f49-8244b7d5f73c)

**Comment by ghost** [comment]
undefined []  
Unexpected token 'T', "The page c"... is not valid JSON

报错，配置如下：
Vercel部署，先fork然后import部署的，一键部署无法使用。配置了环境变量：
VITE_MIDJOURNEY_PROXY_API_SECRET=78910
VITE_MIDJOURNEY_PROXY_URL=https://xxxx.zeabur.app/（xxxx为子域名）

**Comment by gakukinn** [comment]
没看懂

**Comment by gakukinn** [comment]
> 未定义 [] 意外标记“T”、“页面 c”...不是有效的 JSON
> 
> 报错，配置如下： Vercel部署，先fork然后import部署的，一键部署无法使用。配置了环境变量： VITE_MIDJOURNEY_PROXY_API_SECRET=78910 VITE_MIDJOURNEY_PROXY_URL=[https://xxxx.zeabur.app/（xxxx为子域名）](https://xxxx.zeabur.app/%EF%BC%88xxxx%E4%B8%BA%E5%AD%90%E5%9F%9F%E5%90%8D%EF%BC%89)

没看懂
