### ISSUE TITLE
🚰 部署问题反馈--云服务器部署无法访问

### ISSUE THREAD

**Issue by yigeimuya** [ConnectAI-E/MidJourney-Web#16]
## 问题描述 🤔

本地运行没问题，云服务器部署后无法访问。

直接拉取仓库代码运行后是访问地址是，localhost:5173；

vite.config.ts中增加host : ‘0.0.0.0’ 后，在一台服务器部署是内网IP:5173；另一台部署后是公网ip:5173，均无法正常访问。

## 附加信息 📝

为了更好地了解您遇到的问题，我们需要您提供以下信息：

![image](https://github.com/ConnectAI-E/MidJourney-Web/assets/129144058/d1cdeb20-5ff8-4bf7-b0d9-0425b12cd750)

![image](https://github.com/ConnectAI-E/MidJourney-Web/assets/129144058/ac113cea-baa0-454a-8dea-81e3edd29053)
![image](https://github.com/ConnectAI-E/MidJourney-Web/assets/129144058/dafb4cc1-e430-4287-8fea-110cf44bb8a5)

**Comment by lucker168** [comment]
我部署的web 也有同样的问题
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    37392 root   36u  IPv4 477672      0t0  TCP localhost:5173 (LISTEN)
使用 --host 映射主机IP  报错 无效的IP

部署的API 能够通过这个IP 访问 ， 生成图片
