### ISSUE TITLE
用户发现了一个严重的bug，Mijdourney没法出图了

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/MidJourney-Web#39]

**Comment by steveyang687** [comment]
+1，现在持续处于thinking了
![image](https://github.com/ConnectAI-E/MidJourney-Web/assets/32270119/28628050-35e0-461b-98e8-3963d8a75f80)

**Comment by autonomousSpace** [comment]
I am facing the same problem. How did you fix this?
