### ISSUE TITLE
🐞 错误报告 - 正确部署，但无法使用

### ISSUE THREAD

**Issue by Wu-jiyan** [ConnectAI-E/MidJourney-Web#9]
# 错误报告 🐞

## 错误描述 🤔

部署后页面正常显示，但使用时报错
Unexpected token 'T', "The page c"... is not valid JSON
部署方式：vercel
站点链接：https://aidraw.wujiyan.cc/

## 附加信息 📝

控制台输出：
![Snipaste_2023-06-24_19-16-04.png](https://image.wujiyan.cc/imgs/2023/06/24/6496d09ed4115.png)

**Comment by Leizhenpeng** [comment]
后端api有部署么

**Comment by Wu-jiyan** [comment]
> 后端api有部署么

部署了，用的是Zeabur，链接我就不发了

**Comment by Leizhenpeng** [comment]
刚提了一个pr~

**Comment by yigeimuya** [comment]
同样问题
